CREATE TABLE "DB2APPUSER"."CUSTOMER" (
		"CID" BIGINT NOT NULL,
		"FIRST_NAME" VARCHAR(100),
		"LAST_NAME" VARCHAR(100)
	);

ALTER TABLE "DB2APPUSER"."CUSTOMER" ADD CONSTRAINT "PK_CUSTOMER" PRIMARY KEY ("CID");