DROP TABLE CUSTOMER;
	
CREATE TABLE "CUSTOMER" (
	"CID" BIGINT GENERATED ALWAYS AS IDENTITY, 
	"FIRST_NAME" VARCHAR(100), 
	"LAST_NAME" VARCHAR(100));

ALTER TABLE "CUSTOMER" ADD CONSTRAINT "PK_CUSTOMER" PRIMARY KEY ("CID");

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Homer', 'Simpson');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Marge', 'Simpson');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Ned', 'Flanders');

SELECT * FROM CUSTOMER
