DROP TABLE DB2APPUSER.CUSTOMER;
	
CREATE TABLE "DB2APPUSER"."CUSTOMER" (
	"CID" BIGINT GENERATED ALWAYS AS IDENTITY, 
	"FIRST_NAME" VARCHAR(100), 
	"LAST_NAME" VARCHAR(100));

ALTER TABLE "DB2APPUSER"."CUSTOMER" ADD CONSTRAINT "PK_CUSTOMER" PRIMARY KEY ("CID");

INSERT INTO DB2APPUSER.CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Homer', 'Simpson');
INSERT INTO DB2APPUSER.CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Marge', 'Simpson');
INSERT INTO DB2APPUSER.CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Ned', 'Flanders');

SELECT * FROM DB2APPUSER.CUSTOMER